// Generated by CoffeeScript 1.6.3
(function() {
  var MathHelpers;

  MathHelpers = (function() {
    function MathHelpers() {}

    MathHelpers.prototype.sign = function(value) {
      if (value < 0) {
        return -1;
      }
      return 1;
    };

    MathHelpers.prototype.findTurningPoints = function(values) {
      var i, signA, signB, turningPoints, _i, _ref;
      turningPoints = [];
      for (i = _i = 1, _ref = values.length - 1; 1 <= _ref ? _i < _ref : _i > _ref; i = 1 <= _ref ? ++_i : --_i) {
        signA = this.sign(values[i] - values[i - 1]);
        signB = this.sign(values[i + 1] - values[i]);
        if (signA !== signB) {
          turningPoints.push(i);
        }
      }
      return turningPoints;
    };

    MathHelpers.prototype.areaBetweenLineAndCurve = function(values, start, end) {
      var area, curveValue, i, length, lineValue, yEnd, yStart, _i;
      length = end - start;
      yStart = values[start];
      yEnd = values[end];
      area = 0;
      for (i = _i = 0; 0 <= length ? _i <= length : _i >= length; i = 0 <= length ? ++_i : --_i) {
        curveValue = values[start + i];
        lineValue = yStart + (i / length) * (yEnd - yStart);
        area += Math.abs(lineValue - curveValue);
      }
      return area;
    };

    return MathHelpers;

  })();

  module.exports = new MathHelpers;

}).call(this);
