// Generated by CoffeeScript 1.6.3
(function() {
  var HardSwayEasing, SwayEasing, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SwayEasing = require("./sway");

  HardSwayEasing = (function(_super) {
    __extends(HardSwayEasing, _super);

    function HardSwayEasing() {
      _ref = HardSwayEasing.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HardSwayEasing.prototype.oscillation = function(t) {
      return Math.abs(Math.sin(this.omega * t));
    };

    return HardSwayEasing;

  })(SwayEasing);

  module.exports = HardSwayEasing;

}).call(this);
