// Generated by CoffeeScript 1.6.3
(function() {
  var Component, EasingClasses, Matrix4D;

  Matrix4D = require("../math/matrix4d");

  EasingClasses = {
    bounce: require("../easing/bounce"),
    sway: require("../easing/sway"),
    hardbounce: require("../easing/hardbounce"),
    hardsway: require("../easing/hardsway")
  };

  Component = (function() {
    Component.prototype.easing = "bounce";

    Component.prototype.duration = 1000;

    Component.prototype.delay = 0;

    Component.prototype.from = null;

    Component.prototype.to = null;

    function Component(options) {
      options || (options = {});
      if (options.easing != null) {
        this.easing = options.easing;
      }
      if (options.duration != null) {
        this.duration = options.duration;
      }
      if (options.delay != null) {
        this.delay = options.delay;
      }
      if (options.from != null) {
        this.from = options.from;
      }
      if (options.to != null) {
        this.to = options.to;
      }
      this.easingObject = new EasingClasses[this.easing](options);
    }

    Component.prototype.calculateEase = function(ratio) {
      return this.easingObject.calculate(ratio);
    };

    Component.prototype.getMatrix = function() {
      return new Matrix4D().identity();
    };

    Component.prototype.getEasedMatrix = function(ratio) {
      return this.getMatrix();
    };

    Component.prototype.serialize = function() {
      var key, serialized, value, _ref;
      serialized = {
        type: this.constructor.name.toLowerCase(),
        easing: this.easing,
        duration: this.duration,
        delay: this.delay,
        from: this.from,
        to: this.to
      };
      _ref = this.easingObject.serialize();
      for (key in _ref) {
        value = _ref[key];
        serialized[key] = value;
      }
      return serialized;
    };

    return Component;

  })();

  module.exports = Component;

}).call(this);
